Local storage
ewynx/shelter_in_place pull request #24
Opened 2020-05-27 01:36 UTC by peterbertel

The pull request introduces the initial implementation of the local storage. Each new Day will be saved to a backend database json file. The contents of this file will persist until the app is deleted from the user's device. The new BackendService invokes each of these actions for submitting data to and retrieving data from the database.

This pull request will also update the new_summary.dart page, which will create new Day objects based on the contents in the backend database file.

For testing purposes, add several new days by refreshing the app after each successful entry. In a future update, we will update the logic to only allow one entry per day.

2020-06-02 20:12 UTC, ewynx requested changes
Works like a charm!! Awesome 👍 
I added some comments, it's probably code that can all be removed, so just for the sake of cleanness :)

2020-06-02 20:12 UTC, ewynx commented on lib/pages/questions/questions_controller.dart
> +        // await dayService.addDocument(day.toJson());
what should happen with this line?

2020-06-02 20:12 UTC, ewynx commented on lib/pages/summary/new_summary.dart
> +    // Day day1 = Day(
can be removed?

2020-06-02 20:12 UTC, ewynx commented on lib/pages/summary/new_summary.dart
> +    // List<Day> days = [day1, day2, day3, day4, day5, day6, day7, day8, day9, day10, day11];
dito :D

2020-06-02 20:12 UTC, ewynx commented on lib/services/backend_service.dart
> +    // final directory = await getTemporaryDirectory();
can this be removed?

2020-06-02 20:21 UTC, ewynx commented on lib/pages/summary/new_summary.dart
> +    // Day day1 = Day(
actually the definition of all days day1, day2 etc can be removed!

2020-06-04 21:36 UTC, peterbertel commented on lib/services/backend_service.dart
> +    // final directory = await getTemporaryDirectory();
Yep, I removed it in [this commit](https://github.com/ewynx/shelter_in_place/pull/24/commits/53ca9c64c536a774cb80555dbeaf4d3205193c59).

2020-06-04 21:36 UTC, peterbertel commented on lib/pages/summary/new_summary.dart
> +    // List<Day> days = [day1, day2, day3, day4, day5, day6, day7, day8, day9, day10, day11];
Deleted in [this commit](https://github.com/ewynx/shelter_in_place/pull/24/commits/53ca9c64c536a774cb80555dbeaf4d3205193c59).

2020-06-04 21:37 UTC, peterbertel commented on lib/pages/summary/new_summary.dart
> +    // Day day1 = Day(
I deleted all the unused Day objects in [this commit](https://github.com/ewynx/shelter_in_place/pull/24/commits/53ca9c64c536a774cb80555dbeaf4d3205193c59).

2020-06-04 21:38 UTC, peterbertel commented on lib/pages/questions/questions_controller.dart
> +        // await dayService.addDocument(day.toJson());
It wasn't providing any extra functionality for the backend storage, so I had originally just commented it out. I think we can safely delete it, so I did in [this commit](https://github.com/ewynx/shelter_in_place/pull/24/commits/53ca9c64c536a774cb80555dbeaf4d3205193c59).

2020-06-04 21:39 UTC, peterbertel commented
@ewynx I deleted all the unnecessary code you referenced in your comments, so I am going to merge in the changes.

2020-06-04 21:39 UTC, merged